/**
 * Category
 */
export const FETCH_ALL_CATEGORY = 'FETCH_ALL_CATEGORY';
export const FETCH_ALL_CATEGORY_SUCCESS = 'FETCH_ALL_CATEGORY_SUCCESS';
export const FETCH_ALL_CATEGORY_FAIL = 'FETCH_ALL_CATEGORY_FAIL';

/**
 * Product
 */
export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS';
export const FETCH_ALL_PRODUCTS_SUCCESS = 'FETCH_ALL_PRODUCTS_SUCCESS';
export const FETCH_ALL_PRODUCTS_FAIL = 'FETCH_ALL_PRODUCTS_FAIL';

/**
 * User
 */
export const NORMAL_LOGIN = 'NORMAL_LOGIN';
export const NORMAL_LOGIN_SUCCESS = 'NORMAL_LOGIN_SUCCESS';
export const NORMAL_LOGIN_FAIL = 'NORMAL_LOGIN_FAIL';
export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGOUT = 'LOGOUT';

/**
 * Agency
 */
export const GET_AGENCY_SUCCESS = 'GET_AGENCY_SUCCESS';
export const GET_AGENCY_FAIL = 'GET_AGENCY_FAIL';

